server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: citas
              uri: lb://CITAS
              predicates:
                - Path=/api/v1/citas/**,/api/v2/citas/**

            - id: agenda
              uri: lb://AGENDA-MEDICA
              predicates:
                - Path=/api/v1/agendas/**,/api/v2/agendas/**

            - id: evaluacion
              uri: lb://EVALUACION-ATENCION
              predicates:
                - Path=/api/v1/evaluaciones/**,/api/v2/evaluaciones/**

            - id: historial
              uri: lb://HISTORIAL-CLINICO
              predicates:
                - Path=/api/v1/historiales/**,/api/v2/historiales/**

            - id: notificacion
              uri: lb://NOTIFICACION
              predicates:
                - Path=/api/v1/notificaciones/**,/api/v2/notificaciones/**

            - id: pagos
              uri: lb://PAGOS
              predicates:
                - Path=/api/v1/pagos/**,/api/v2/pagos/**

            - id: receta
              uri: lb://RECETA-MEDICA
              predicates:
                - Path=/api/v1/recetas/**,/api/v2/recetas/**

            - id: videollamada
              uri: lb://VIDEOLLAMADA
              predicates:
                - Path=/api/v1/videollamadas/**,/api/v2/videollamadas/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}