spring.datasource.url=jdbc:mysql://mysql-evaluacion:3306/evaluacion_atencion
spring.datasource.username=root
spring.datasource.password=root

eureka.client.service-url.defaultZone=http://medilink-eureka-server:8761/eureka