spring.datasource.url=jdbc:mysql://medilink-mysql-pago:3306/pago
spring.datasource.username=root
spring.datasource.password=root

eureka.client.service-url.defaultZone=http://medilink-eureka-server:8761/eureka